"""Configuration package"""

from .settings import (
    MODEL_OPTIONS,
    SAMPLE_TEXTS,
    DEFAULT_CHUNK_SIZE,
    DEFAULT_OVERLAP,
    DEFAULT_COLLECTION_NAME,
    DEFAULT_N_RESULTS,
    DEFAULT_REDUCTION_METHOD,
    DEFAULT_MODEL,
    DEFAULT_TEMPERATURE,
    DEFAULT_SYSTEM_PROMPT,
)

__all__ = [
    'MODEL_OPTIONS',
    'SAMPLE_TEXTS',
    'DEFAULT_CHUNK_SIZE',
    'DEFAULT_OVERLAP',
    'DEFAULT_COLLECTION_NAME',
    'DEFAULT_N_RESULTS',
    'DEFAULT_REDUCTION_METHOD',
    'DEFAULT_MODEL',
    'DEFAULT_TEMPERATURE',
    'DEFAULT_SYSTEM_PROMPT',
]

